### ISSUE TITLE
Cant catch throttle up/down event from my joystick

### ISSUE THREAD

**Issue by freylis** [pbuckner/xppython3-demos#1]
I write plugin for my custom arduino panel and i want to send some flight params after it changes by joy/keyboard. Now i have this code and it works for keyboard, but dont for joystick **_logitech extreme 3d pro_**
```python

# define callbacks for throttle / gear
def gear_changes_callback(commandRef, phase, refCon):
    gear_ref = xp.findDataRef('sim/cockpit/switches/gear_handle_status')
    gear_ref_val = xp.getDatai(gear_ref)
    xp.log(f'Gear changed. Current gear: {gear_ref_val}')

    # future code will send message to COM port for arduino
    return 1


def throttle_changes_callback(commandRef, phase, refCon):
    throttle_ref = xp.findDataRef('sim/cockpit2/engine/actuators/throttle_ratio_all')
    throttle_val = xp.getDataf(throttle_ref)
    xp.log(f'Throttle changed. Current throttle: {throttle_val}')
    # future code will send message to COM port for arduino
    return 1


# subscribe for some commands
for cmd, callback in (
    # about gear
    ('sim/flight_controls/landing_gear_up', gear_changes_callback),
    ('sim/flight_controls/landing_gear_down', gear_changes_callback),
    ('sim/flight_controls/landing_gear_toggle', gear_changes_callback),
    # about throttle
    ('sim/engines/throttle_up', throttle_changes_callback),
    ('sim/engines/throttle_down', throttle_changes_callback),
):
    command = xp.findCommand(cmd)
    xp.registerCommandHandler(command, callback)
```

1. I run xplane, load Baron B58 aircraft
2. Take my keyboard
3. Press "G" button
4. I see in log messages about gear changes
5. Press "F1" or "F2" buttons and i see log messages about throttle changes

Okey, its great! Lets do it with joy:
1. Take my joystick
2. Press joy button "10" (my toggle gear button)
3. I see log messages about gear up/down
4. I move throttle button ("+/-" controller)
5. ... and it does not works((

Help me please. How can i catch  +/- throttle events from my joystick ?

**Comment by pbuckner** [comment]
likely not a python issue. View updates to this question on your thread on x-plane.org.

**Comment by freylis** [comment]
> likely not a python issue. View updates to this question on your thread on x-plane.org.

I think its python issue. Command callback works only with keyboard changes and doesnt works with **mouse**/joystick changes: **Touch GEAR UP/DOWN with mouse in cockpit doesnt call a callback, but press "G" button  does**

**Comment by pbuckner** [comment]
Please followup at https://forums.x-plane.org/index.php?/forums/topic/259696-cant-catch-throttle-updown-event-from-my-joystick/ rather than here on github.
